name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - id: pre-step
        shell: bash
        run: echo "release_tag=$(date +%d-%m-%Y-%s)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Python
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./development
          file: ./development/Dockerfile.python311
          tags: torbendury/python-dev:3.11-${{ steps.pre-step.outputs.release_tag }},torbendury/python-dev:latest
      - name: Build and push Golang
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./development
          file: ./development/Dockerfile.golang120
          tags: torbendury/golang-dev:1.20.4-${{ steps.pre-step.outputs.release_tag }},torbendury/golang-dev:latest
